services:
  suculentas_web:
    container_name: suculentas_web
    build:
      context: .
    ports:
      - "43127:3000"
    volumes:
      - ./web:/app
      - /app/node_modules
      - /app/.next
      - ./data/media:/app/public/media
    env_file:
      - ./dotenv_files/.env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-suculentas_user}:${POSTGRES_PASSWORD:-Suculentas1234}@suculentas_psql:5432/${POSTGRES_DB:-suculentas}?schema=public
      POSTGRES_HOST: suculentas_psql
      POSTGRES_PORT: "5432"
      AUTH_URL: http://127.0.0.1:43127
      NEXTAUTH_URL: http://127.0.0.1:43127
    depends_on:
      - suculentas_psql
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 1.1.1.1

  suculentas_psql:
    container_name: suculentas_psql
    image: postgres:16-alpine
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - ./dotenv_files/.env
    ports:
      - "43128:5432"
    restart: unless-stopped
